name: Build Doc Site

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
      - name: Build Doc Site
        run: |
          cd doc-site
          yarn install
          yarn run build