name: Check required files

on:
  pull_request:
    branches: [master]

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check required files
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          echo $CHANGED_FILES

          if ! grep -q "etiennethompson-ui" <<< $CHANGED_FILES; then
            echo "No etiennethompson-ui changes."
            exit 0
          fi

          if grep -q "etiennethompson-ui" <<< $CHANGED_FILES; then
            if ! grep -q "etiennethompson-ui/package.json" <<< $CHANGED_FILES; then
              echo "etiennethompson-ui changed without package.json version update."
              exit 1
            fi
          fi

          CHANGED_LINES=$(git diff --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} etiennethompson-ui/package.json)
          echo $CHANGED_LINES

          VERSION_REGEX='"version": "[0-9]+\.[0-9]+\.[0-9]+"'
          VERSIONS=$(grep -o $VERSION_REGEX <<< $CHANGED_LINES)
          echo $VERSIONS
