name: Check required files

on:
  pull_request:
    branches: [master]

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check required files
        run: |
          BRANCH_NAME=$(git branch --show-current)
          echo $BRANCH_NAME
          CHANGED_FILES=$(git diff --name-only master...$BRANCH_NAME)
          echo $CHANGED_FILES