name: Check required files

on:
  pull_request:
    branches: [master]

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check required files
      run: |
        CHANGED_FILES=$(git diff --name-only master)
        echo $CHANGED_FILES